version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/qor5/admin"
  cyclomatic_complexity_threshold = "high"

[[transformers]]
name = "gofumpt"