package seo

import (
	"errors"
	"fmt"
	"net/url"
	"reflect"
	"strings"

	"github.com/go-playground/form"
	"github.com/goplaid/web"
	"github.com/goplaid/x/presets"
	. "github.com/goplaid/x/vuetify"
	h "github.com/theplant/htmlgo"
	"gorm.io/gorm"
)

const (
	saveCollectionEvent = "seo_save_collection"
)

func (collection *Collection) Configure(b *presets.Builder, db *gorm.DB) {
	err := db.AutoMigrate(
		collection.settingModel,
	)

	if err != nil {
		panic(err)
	}

	b.GetWebBuilder().RegisterEventFunc(saveCollectionEvent, saveCollection(collection, db))
	b.Model(collection.settingModel).PrimaryField("Name").Label("SEO").Listing().PageFunc(collection.pageFunc(db))

	b.FieldDefaults(presets.WRITE).
		FieldType(Setting{}).
		ComponentFunc(SeoEditingComponentFunc(collection))
}

func SeoEditingComponentFunc(collection *Collection) presets.FieldComponentFunc {
	return func(obj interface{}, field *presets.FieldContext, ctx *web.EventContext) h.HTMLComponent {
		return collection.settingComponent(obj)
	}
}

func (collection *Collection) pageFunc(db *gorm.DB) web.PageFunc {
	return func(ctx *web.EventContext) (r web.PageResponse, err error) {
		r.PageTitle = "SEO Setting"
		r.Body = VContainer(
			VSnackbar(h.Text("Saved successfully")).
				Attr("v-model", "vars.seoSnackbarShow").
				Top(true).
				Color("primary").
				Timeout(2000),
			VRow(
				VCol(
					VContainer(
						h.H3("Site-wide Settings").Style("font-weight: 500"),
						h.P().Text("Here you can set site-wide variables and preferences for metadata.")),
				).Cols(3),
				VCol(
					VCard(
						VForm(
							collection.renderGlobalSection(db),
						),
					).Outlined(true).Elevation(2),
				).Cols(9),
			),
			VRow(
				VCol(
					VContainer(
						h.H3("Page Metadata Defaults").Attr("style", "font-weight: 500"),
						h.P().Text("These defaults are for pages automatically generated by the system, you can override them on the individual pages.")),
				).Cols(3),
				VCol(
					VExpansionPanels(
						collection.renderSeoSections(db),
					).Focusable(true),
				).Cols(9),
			),
		).Attr("style", "background-color: #f5f5f5;max-width:100%").Attr(web.InitContextVars, `{seoSnackbarShow: false}`)

		return
	}
}

func (collection *Collection) renderGlobalSection(db *gorm.DB) h.HTMLComponent {
	setting := reflect.New(reflect.Indirect(reflect.ValueOf(collection.settingModel)).Type()).Interface().(QorSEOSettingInterface)
	err := db.Where("is_global_seo = ? AND name = ?", true, collection.Name).First(setting).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		setting.SetName(collection.Name)
		setting.SetSEOType(collection.Name)
		setting.SetIsGlobalSEO(true)
		db.Save(setting)
	}

	value := reflect.Indirect(reflect.ValueOf(collection.globalSetting))
	settingValue := setting.GetGlobalSetting()
	for i := 0; i < value.NumField(); i++ {
		fieldName := value.Type().Field(i).Name
		if settingValue[fieldName] != "" {
			value.Field(i).Set(reflect.ValueOf(settingValue[fieldName]))
		}
	}

	var comps h.HTMLComponents
	for i := 0; i < value.Type().NumField(); i++ {
		filed := value.Type().Field(i)
		comps = append(comps, VTextField().FieldName(fmt.Sprintf("%s.%s", collection.Name, filed.Name)).Label(filed.Name).Value(value.Field(i).String()).Clearable(true))
	}

	return VForm(
		VCardText(
			comps,
		),

		VCardActions(
			VSpacer(),
			VBtn("Save").Bind("loading", "vars.global_seo_loading").Color("primary").Large(true).Attr("@click", web.Plaid().EventFunc(saveCollectionEvent, collection.Name, "global_seo_loading").BeforeScript(`vars.global_seo_loading = true;`).Go()),
		).Attr(web.InitContextVars, `{global_seo_loading: false}`),
	)
}

func (collection *Collection) renderSeoSections(db *gorm.DB) h.HTMLComponents {
	var comps h.HTMLComponents
	for _, seo := range collection.registeredSEO {
		setting := reflect.New(reflect.Indirect(reflect.ValueOf(collection.settingModel)).Type()).Interface().(QorSEOSettingInterface)
		err := db.Where("name = ?", seo.Name).First(setting).Error
		if errors.Is(err, gorm.ErrRecordNotFound) {
			setting.SetName(seo.Name)
			setting.SetSEOType(seo.Name)
			db.Save(setting)
		}
		setting.SetCollection(collection)

		loadingName := strings.ToLower(seo.Name)
		loadingName = strings.ReplaceAll(loadingName, " ", "_")
		comp := VExpansionPanel(
			VExpansionPanelHeader(h.H4(seo.Name).Style("font-weight: 500;")),
			VExpansionPanelContent(
				VCardText(
					collection.settingComponent(setting),
				),
				VCardActions(
					VSpacer(),
					VBtn("Save").Bind("loading", fmt.Sprintf("vars.%s", loadingName)).Color("primary").Large(true).Attr("@click", web.Plaid().EventFunc(saveCollectionEvent, seo.Name, loadingName).BeforeScript(fmt.Sprintf("vars.%s = true;", loadingName)).Go()),
				).Attr(web.InitContextVars, fmt.Sprintf(`{%s: false}`, loadingName)),
			),
		)

		comps = append(comps, comp)
	}

	return comps
}

func (collection *Collection) settingComponent(obj interface{}) h.HTMLComponents {
	var (
		fieldPrefix string
		isModel     bool
		seo         *SEO
		setting     Setting
	)

	if qorSeoSetting, ok := obj.(QorSEOSettingInterface); ok {
		fieldPrefix = qorSeoSetting.GetName()
		seo = collection.GetSEO(fieldPrefix)
		setting = qorSeoSetting.GetSEOSetting()
	} else {
		if seoInterface, ok := obj.(interface{ GetSEO() *SEO }); ok {
			isModel = true
			seo = seoInterface.GetSEO()
			value := reflect.Indirect(reflect.ValueOf(obj))
			for i := 0; i < value.NumField(); i++ {
				if s, ok := value.Field(i).Interface().(Setting); ok {
					setting = s
					fieldPrefix = value.Type().Field(i).Name
				}
			}
		} else {
			return nil
		}
	}

	var variables []string
	value := reflect.Indirect(reflect.ValueOf(collection.globalSetting)).Type()
	for i := 0; i < value.NumField(); i++ {
		fieldName := value.Field(i).Name
		variables = append(variables, fieldName)
	}
	variables = append(variables, seo.Variables...)

	var variablesEle []h.HTMLComponent
	for _, variable := range variables {
		variablesEle = append(variablesEle, VCol(
			VBtn("").Width(100).Icon(true).Children(VIcon("add_box"), h.Text(variable)),
		).Cols(2))
	}

	commonSettingComponent := h.Components(
		VRow(
			variablesEle...,
		),
		h.H6("Basic").Style("margin-top:15px;margin-bottom:15px;"),
		VCard(
			VCardText(
				VTextField().Counter(65).FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "Title")).Label("Title").Value(setting.Title).Clearable(true),
				VTextField().Counter(150).FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "Description")).Label("Description").Value(setting.Description).Clearable(true),
				VTextarea().Counter(255).Rows(2).AutoGrow(true).FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "Keywords")).Label("Keywords").Value(setting.Keywords).Clearable(true),
			),
		).Color("#f5f5f5").Elevation(0),
		h.H6("Open Graph Information").Style("margin-top:15px;margin-bottom:15px;"),
		VCard(
			VCardText(
				VRow(
					VCol(VTextField().FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "OpenGraphURL")).Label("Open Graph URL").Value(setting.OpenGraphURL).Clearable(true)).Cols(6),
					VCol(VTextField().FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "OpenGraphType")).Label("Open Graph Type").Value(setting.OpenGraphType).Clearable(true)).Cols(6),
				),
				VRow(
					VCol(VTextField().FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "OpenGraphImageURL")).Label("Open Graph Image URL").Value(setting.OpenGraphImageURL).Clearable(true)).Cols(6),
					VCol(VTextField().FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "OpenGraphImageFromMediaLibrary")).Label("Open Graph Image").Clearable(true)).Cols(6),
				),
			),
		).Color("#f5f5f5").Elevation(0),
	)

	if !isModel {
		return commonSettingComponent
	}

	return h.HTMLComponents{
		h.Label(fieldPrefix).Class("v-label theme--light"),
		VCard(
			VCardText(
				VSwitch().FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "UserDefaults")).Label("Use Defaults").Attr("v-model", "vars.userDefaults").On("change", "vars.enabledCustomize = !vars.userDefaults;$refs.customize.$emit('change', vars.enabledCustomize)"),
				VSwitch().FieldName(fmt.Sprintf("%s.%s", fieldPrefix, "EnabledCustomize")).Label("EnabledCustomize").Attr(":input-value", "vars.enabledCustomize").Attr("ref", "customize").Attr("style", "display:none"),
				h.Div(commonSettingComponent).Attr("v-show", "vars.userDefaults == false"),
			).Attr("style", "padding-bottom: 0px;padding-top: 1px;"),
		).Attr(web.InitContextLocals, fmt.Sprintf(`{enabledCustomize: %t, userDefaults: %t}`, setting.EnabledCustomize, !setting.EnabledCustomize)),
	}
}

func saveCollection(collection *Collection, db *gorm.DB) web.EventFunc {
	return func(ctx *web.EventContext) (r web.EventResponse, err error) {
		if len(ctx.Event.Params) != 2 {
			return
		}

		prefix := ctx.Event.Params[0]

		setting := reflect.New(reflect.Indirect(reflect.ValueOf(collection.settingModel)).Type()).Interface().(QorSEOSettingInterface)
		err = db.Where("name = ?", prefix).First(setting).Error
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return
		}

		if setting.GetIsGlobalSEO() {
			globalSetting := make(map[string]string)
			for fieldWithPrefix := range ctx.R.Form {
				if strings.HasPrefix(fieldWithPrefix, prefix) {
					field := strings.Replace(fieldWithPrefix, fmt.Sprintf("%s.", prefix), "", -1)
					globalSetting[field] = ctx.R.Form.Get(fieldWithPrefix)
				}
			}
			setting.SetGlobalSetting(globalSetting)
		} else {
			values := url.Values{}
			for fieldWithPrefix := range ctx.R.Form {
				if strings.HasPrefix(fieldWithPrefix, prefix) {
					field := strings.Replace(fieldWithPrefix, fmt.Sprintf("%s.", prefix), "", -1)
					values[field] = []string{ctx.R.Form.Get(fieldWithPrefix)}
				}
			}
			s := setting.GetSEOSetting()
			decoder := form.NewDecoder()
			// fmt.Println(values)
			decoder.Decode(&s, values)
			setting.SetSEOSetting(s)
		}

		err = db.Save(setting).Error
		if err != nil {
			return
		}

		r.VarsScript = fmt.Sprintf(`vars.seoSnackbarShow = true;vars.%s = false;`, ctx.Event.Params[1])
		return
	}
}
